[package]
name = "double_riichi_mcp"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
rmcp = { version = "=3.4.0", default-features = false, features = ["client", "server", "transport-streamable-http-client-reqwest", "transport-io"] }
tokio = { version = "=1.53.1", features = ["macros", "rt-multi-thread", "io-std"] }
url = "=2.5.8"

[[bin]]
name = "driichi-mcp"
path = "src/main.rs"

[lints]
workspace = true
